name: Quality Check

on:
  push:
    paths:
      - '*.yaml'
      - '*.yml'
      - '*.md'
    branches:
      - "*"
  pull_request:
    paths:
      - '*.yaml'
      - '*.yml'
      - '*.md'

jobs:

  qc:
    name: Code Linting and Validation
    runs-on: ubuntu-latest

    steps:

      - name: Checking Out Branch
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Linting Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Linting Test Compose
        run: |
          yamllint -s tests/*.yaml

      - name: Linting Docs
        run: |
          find ./ -type f -name "*.md" -exec markdownlint {} \;
