name: Quality Check

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  qc:
    name: Linting and Validation
    runs-on: ubuntu-latest

    steps:

      - name: Checking Out Branch
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Linting Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Linting Test
        run: |
          yamllint -s tests/*.yaml

      - name: Linting Docs
        uses: DavidAnson/markdownlint-cli2-action@v16.0.0
        with:
          globs: |
            README.md
